#Spring Boot server configuration
#server:
#  address: 0.0.0.0
#  port: 8000

openai:
    api:
      model: "text-davinci-003"
      temperature: 0.9
      maxTokens: 2048

logging:
  level:
      org:
        springframework:
            web: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    enabled: false
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /openai/completion*
      rate-limits:
        - bandwidths: # maximum of 5 requests within 10 seconds
            - capacity: 5
              time: 10
              unit: seconds
    - cache-name: buckets
      url: /openai/image*
      rate-limits:
        - bandwidths: # maximum of 5 requests within 10 seconds
            - capacity: 5
              time: 10
              unit: seconds
